## 환경 설정

- **작업 디렉터리**: `edupython/application/stock` (이 노트북 위치)
- **환경변수**: `edupython/.env` — `KRX_ID`, `KRX_PW` (`.env.example` 참고)
- 아래 셀에서 `.env` 를 로드한 뒤 `app` 모듈을 import 합니다.

In [ ]:
import sys
from pathlib import Path

EDUPYTHON_ROOT = Path.cwd().parent.parent  # stock → application → edupython
if str(EDUPYTHON_ROOT) not in sys.path:
    sys.path.insert(0, str(EDUPYTHON_ROOT))

from env_loader import load_edupython_env

if load_edupython_env():
    print(f'환경변수 로드: {EDUPYTHON_ROOT / ".env"}')
else:
    print('edupython/.env 없음 또는 python-dotenv 미설치')

In [90]:
import FinanceDataReader as fdr
from app.services.index_constituents import (
    get_sector_indices,
    get_index_constituents,
    fetch_kospi_sector_constituents,
    build_code_to_sector_map,
    apply_sector_to_dataframe,
    enrich_listing_with_sector,
)

ImportError: cannot import name 'fetch_kospi_sector_constituents' from 'app.services.index_constituents' (/home/jang/codespace/colab/stock/flask/app/services/index_constituents.py)

In [29]:
# 1) 섹터 지수 목록 (1005~1027)
sectors = get_sector_indices()
sectors

['1005',
 '1006',
 '1007',
 '1008',
 '1009',
 '1010',
 '1011',
 '1012',
 '1013',
 '1014',
 '1015',
 '1016',
 '1017',
 '1018',
 '1019',
 '1020',
 '1021',
 '1024',
 '1025',
 '1026',
 '1027']

In [91]:
# 2) 섹터별 구성종목 — 캐시 우선 (없으면 KRX API, 최초 1회만 느림)
# edupython/.env (KRX_ID, KRX_PW) 필요 — 위 환경 설정 셀 실행 후 사용
from app.services.index_constituents import warm_sector_cache

sectorList = fetch_kospi_sector_constituents()
print(f'섹터 {len(sectorList)}개')

# dev.ipynb 에서 직접 조회한 sectorList 가 있으면 캐시에 저장 (다음부터 즉시 로드)
# warm_sector_cache(sectorList)

NameError: name 'fetch_kospi_sector_constituents' is not defined

In [92]:
# 3) {섹터코드: [종목코드]} → {종목코드: 섹터명}
sector_map = build_code_to_sector_map(sectorList)
sector_map.get('005930'), sector_map.get('000660')

NameError: name 'build_code_to_sector_map' is not defined

In [33]:
# 4) KRX 종목 목록 + Sector 열
krxList = fdr.StockListing('KRX')
krxList = apply_sector_to_dataframe(krxList, sector_map)
krxList[['Code', 'Name', 'Market', 'Close', 'Sector']].head(10)

In [93]:
# (한 줄) sectorList 를 이미 만들어 둔 경우
# krxList = enrich_listing_with_sector(fdr.StockListing('KRX'), sector_constituents=sectorList)

# 섹터별 종목 수 확인
krxList.groupby('Sector').size().sort_values(ascending=False)

Sector
기타    2875
dtype: int64

In [94]:

sectorList.keys()

dict_keys(['1005', '1006', '1007', '1008', '1009', '1010', '1011', '1012', '1013', '1014', '1015', '1016', '1017', '1018', '1019', '1020', '1021', '1024', '1025', '1026', '1027'])

In [95]:
sectorList

{'1005': ['033780',
  '003230',
  '271560',
  '097950',
  '004370',
  '007310',
  '000080',
  '005300',
  '280360',
  '001680',
  '005180',
  '145990',
  '017810',
  '005610',
  '003920',
  '003960',
  '136490',
  '007160',
  '033920',
  '001790',
  '001130',
  '101530',
  '008040',
  '014710',
  '264900',
  '248170',
  '036580',
  '002600',
  '011150',
  '006090',
  '006980',
  '002140',
  '004410',
  '000890',
  '027740',
  '023150',
  '003680'],
 '1006': ['383220',
  '093050',
  '020000',
  '004700',
  '105630',
  '194370',
  '003200',
  '001460',
  '241590',
  '003610',
  '016450',
  '002170',
  '009270',
  '005800',
  '007980',
  '111380',
  '016090',
  '111110',
  '000950',
  '093240',
  '011300',
  '084870',
  '014990',
  '005820',
  '001070',
  '090370',
  '002070',
  '008500'],
 '1007': ['016590',
  '002310',
  '213500',
  '011280',
  '027970',
  '009580',
  '014160',
  '002200',
  '001020',
  '009200',
  '009770',
  '012690',
  '004540',
  '025750',
  '008250',
  '009460',
  '006740',
  '446070'],
 '1008': ['051910',
  '096770',
  '278470',
  '010950',
  '000880',
  '161390',
  '009830',
  '011790',
  '090430',
  '002380',
  '051900',
  '011170',
  '014680',
  '011780',
  '457190',
  '483650',
  '120110',
  '093370',
  '161890',
  '192820',
  '002790',
  '005070',
  '298020',
  '073240',
  '004000',
  '000210',
  '003240',
  '456040',
  '298050',
  '006650',
  '285130',
  '002350',
  '178920',
  '069260',
  '002960',
  '006380',
  '014820',
  '001570',
  '002840',
  '161000',
  '005420',
  '268280',
  '014830',
  '008730',
  '005950',
  '092230',
  '005720',
  '007690',
  '025860',
  '001390',
  '108670',
  '018250',
  '003720',
  '078520',
  '001340',
  '017860',
  '011500',
  '004430',
  '134380',
  '008490',
  '226320',
  '025000',
  '003650',
  '035150',
  '102260',
  '003350',
  '002100',
  '298000',
  '100250',
  '000860',
  '000390',
  '012610',
  '090350',
  '003830',
  '081000',
  '089470',
  '214420',
  '272550',
  '015890',
  '083420',
  '025620',
  '014530',
  '004250',
  '023450',
  '014440',
  '007590',
  '163560',
  '004840',
  '055490',
  '006890',
  '003780',
  '079980',
  '004830',
  '002760',
  '003080',
  '051630',
  '004910',
  '001550',
  '024070',
  '010640',
  '024890',
  '002820',
  '002360'],
 '1009': ['207940',
  '068270',
  '000100',
  '128940',
  '302440',
  '009420',
  '006280',
  '069620',
  '003090',
  '185750',
  '003850',
  '317450',
  '001060',
  '249420',
  '377740',
  '003000',
  '019170',
  '0120G0',
  '170900',
  '009290',
  '033270',
  '005500',
  '003120',
  '003520',
  '004310',
  '001630',
  '003220',
  '102460',
  '234080',
  '016580',
  '007570',
  '293480',
  '271980',
  '000520',
  '000020',
  '214390',
  '001360',
  '002390',
  '063160',
  '002210',
  '002720',
  '000230',
  '011000',
  '007460',
  '004720',
  '000220',
  '002630',
  '017180',
  '003060'],
 '1010': ['300720',
  '010780',
  '003300',
  '344820',
  '183190',
  '000480',
  '004980',
  '462520',
  '004090',
  '001520',
  '014580',
  '007210',
  '001560',
  '005750',
  '010040',
  '004440',
  '011390',
  '000910',
  '047400',
  '008870',
  '004870'],
 '1011': ['005490',
  '010130',
  '079550',
  '004020',
  '112610',
  '103140',
  '017960',
  '001430',
  '100090',
  '000670',
  '006110',
  '016380',
  '058650',
  '002240',
  '460860',
  '306200',
  '010820',
  '092790',
  '002710',
  '001940',
  '058430',
  '104700',
  '084010',
  '009160',
  '005010',
  '004560',
  '001780',
  '001080',
  '008350',
  '000970',
  '460850',
  '025820',
  '002220',
  '018470',
  '008970',
  '014280',
  '024090',
  '012800',
  '120030',
  '032560',
  '008260',
  '139990',
  '009190',
  '004890',
  '069730',
  '085310',
  '155660',
  '021050',
  '007280',
  '071090',
  '004450',
  '058730',
  '008420',
  '133820',
  '026940',
  '069460',
  '006570',
  '002690',
  '012160',
  '001770'],
 '1012': ['034020',
  '042700',
  '267270',
  '454910',
  '241560',
  '018880',
  '082740',
  '017800',
  '071970',
  '077970',
  '079900',
  '484870',
  '100840',
  '002900',
  '000490',
  '004380',
  '012200',
  '017550',
  '210540',
  '015590',
  '011700',
  '119650',
  '017370',
  '010660',
  '000850',
  '480370',
  '092440',
  '074610',
  '049800',
  '025890',
  '009310',
  '145210'],
 '1013': ['005930',
  '000660',
  '009150',
  '373220',
  '006400',
  '267260',
  '010120',
  '066570',
  '298040',
  '011070',
  '000150',
  '272210',
  '003670',
  '007660',
  '353200',
  '062040',
  '001440',
  '000990',
  '034220',
  '066970',
  '336260',
  '000500',
  '450080',
  '103590',
  '489790',
  '020150',
  '007810',
  '007340',
  '361610',
  '001820',
  '322000',
  '195870',
  '006340',
  '005690',
  '004490',
  '336370',
  '248070',
  '108320',
  '090460',
  '033240',
  '025540',
  '009450',
  '029530',
  '005680',
  '011930',
  '017900',
  '097520',
  '009470',
  '217590',
  '004710',
  '192650',
  '004770',
  '044380',
  '001210',
  '092220',
  '109070',
  '009140',
  '008700',
  '007610',
  '020760',
  '004920',
  '019490',
  '019180',
  '017040',
  '015260',
  '014910',
  '005870',
  '011230',
  '011690'],
 '1014': ['281820',
  '137310',
  '003160',
  '105840',
  '145720',
  '029460',
  '025560',
  '372910'],
 '1015': ['005380',
  '329180',
  '000270',
  '012450',
  '012330',
  '042660',
  '010140',
  '064350',
  '047810',
  '204320',
  '005850',
  '439260',
  '011210',
  '003570',
  '075580',
  '064960',
  '003620',
  '009900',
  '271940',
  '010690',
  '200880',
  '092200',
  '000430',
  '009680',
  '033530',
  '010580',
  '013520',
  '000300',
  '015230',
  '004100',
  '021820',
  '018500',
  '016740',
  '023800',
  '023000',
  '006660',
  '010100',
  '308170',
  '214330',
  '143210',
  '123700',
  '092780',
  '090080',
  '075180',
  '041650',
  '033250',
  '024900',
  '023810',
  '012280',
  '011330',
  '010770',
  '009320',
  '005030',
  '002920',
  '002880',
  '001620',
  '001380',
  '000040',
  '013870',
  '378850',
  '001420'],
 '1016': ['028260',
  '047050',
  '004170',
  '023530',
  '069960',
  '111770',
  '026960',
  '139480',
  '001740',
  '008770',
  '081660',
  '282330',
  '018670',
  '007070',
  '001120',
  '009240',
  '017940',
  '453340',
  '031430',
  '452260',
  '001530',
  '381970',
  '002810',
  '011760',
  '037710',
  '001250',
  '000680',
  '122900',
  '475560',
  '000050',
  '128820',
  '339770',
  '077500',
  '006060',
  '071840',
  '004080',
  '227840',
  '011810',
  '123690',
  '067830',
  '007110',
  '002700',
  '003580',
  '003010',
  '101140',
  '006880',
  '004060',
  '025530',
  '005320',
  '000760',
  '013000',
  '006370',
  '002420',
  '005360',
  '118000',
  '002870',
  '088790',
  '009810',
  '005110',
  '069640',
  '004270',
  '008600'],
 '1017': ['015760',
  '036460',
  '071320',
  '005090',
  '004690',
  '017390',
  '117580',
  '003480',
  '267290',
  '034590'],
 '1018': ['000720',
  '047040',
  '375500',
  '006360',
  '051600',
  '097230',
  '475150',
  '294870',
  '009410',
  '126720',
  '003070',
  '028100',
  '039570',
  '013580',
  '002990',
  '005960',
  '002780',
  '002460',
  '004960',
  '014790',
  '013360',
  '010960',
  '001470',
  '001260',
  '013700',
  '002410',
  '023960',
  '010400'],
 '1019': ['011200',
  '086280',
  '003490',
  '028670',
  '000120',
  '020560',
  '005880',
  '003280',
  '089590',
  '091810',
  '272450',
  '000650',
  '005430',
  '002320',
  '004360',
  '044450',
  '298690',
  '009070',
  '084670',
  '004140',
  '009180',
  '129260',
  '014130',
  '465770'],
 '1020': ['017670', '030200', '032640', '126560', '006490'],
 '1021': ['402340',
  '032830',
  '105560',
  '055550',
  '034730',
  '086790',
  '009540',
  '000810',
  '006800',
  '316140',
  '267250',
  '138040',
  '024110',
  '003550',
  '071050',
  '006260',
  '005940',
  '323410',
  '0126Z0',
  '016360',
  '005830',
  '039490',
  '180640',
  '078930',
  '377300',
  '029780',
  '010060',
  '138930',
  '088350',
  '175330',
  '001040',
  '088980',
  '085620',
  '001450',
  '004800',
  '001720',
  '031210',
  '139130',
  '279570',
  '004990',
  '000240',
  '003690',
  '009970',
  '005440',
  '229640',
  '008930',
  '001800',
  '006040',
  '003540',
  '030610',
  '012630',
  '415640',
  '082640',
  '003530',
  '499790',
  '003470',
  '192400',
  '000370',
  '036530',
  '006120',
  '001510',
  '002020',
  '000400',
  '003030',
  '383800',
  '007700',
  '008060',
  '001270',
  '001500',
  '000640',
  '005810',
  '000070',
  '006220',
  '001200',
  '072710',
  '060980',
  '027410',
  '016610',
  '001230',
  '034830',
  '015860',
  '244920',
  '096760',
  '000540',
  '026890',
  '024720',
  '123890',
  '001750',
  '000320',
  '0030R0',
  '084690',
  '000140',
  '003460',
  '004150',
  '007860',
  '016880',
  '030210',
  '044820',
  '487570',
  '000590',
  '001290',
  '005740',
  '006840',
  '363280',
  '012320',
  '013570',
  '107590',
  '007540',
  '481850',
  '009440',
  '006200'],
 '1024': ['006800',
  '005940',
  '016360',
  '039490',
  '001720',
  '003540',
  '030610',
  '003530',
  '003470',
  '001510',
  '001270',
  '001500',
  '016610',
  '001200',
  '001750',
  '030210',
  '003460',
  '001290'],
 '1025': ['032830',
  '000810',
  '005830',
  '088350',
  '085620',
  '001450',
  '031210',
  '003690',
  '082640',
  '000370',
  '000400',
  '000540'],
 '1026': ['028050',
  '443060',
  '326030',
  '021240',
  '052690',
  '022100',
  '012750',
  '030000',
  '032350',
  '089860',
  '214320',
  '039130',
  '005250',
  '284740',
  '130660',
  '034310',
  '403550',
  '015360',
  '002030',
  '053690',
  '095570',
  '002150',
  '031440',
  '000700',
  '094280',
  '070960',
  '002620',
  '016710',
  '035000',
  '019680',
  '095720',
  '000180',
  '023350'],
 '1027': ['005930',
  '000660',
  '009150',
  '005380',
  '373220',
  '329180',
  '000270',
  '034020',
  '012450',
  '207940',
  '012330',
  '006400',
  '267260',
  '042660',
  '010120',
  '068270',
  '066570',
  '298040',
  '042700',
  '005490',
  '011070',
  '000150',
  '010130',
  '051910',
  '010140',
  '064350',
  '079550',
  '272210',
  '033780',
  '096770',
  '003670',
  '278470',
  '047810',
  '010950',
  '000880',
  '007660',
  '003230',
  '353200',
  '161390',
  '001440',
  '267270',
  '062040',
  '009830',
  '034220',
  '454910',
  '000990',
  '011790',
  '090430',
  '241560',
  '000100',
  '066970',
  '018880',
  '336260',
  '128940',
  '271560',
  '082740',
  '004020',
  '002380',
  '000500',
  '103590',
  '450080',
  '051900',
  '204320',
  '489790',
  '005850',
  '017800',
  '014680',
  '011780',
  '011170',
  '020150',
  '302440',
  '097950',
  '383220',
  '007810',
  '439260',
  '457190',
  '483650',
  '009420',
  '071970',
  '007340',
  '093370',
  '103140',
  '112610',
  '004370',
  '161890',
  '192820',
  '011210',
  '120110',
  '322000',
  '006280',
  '077970',
  '195870',
  '281820',
  '298020',
  '017960',
  '069620',
  '073240',
  '001430',
  '001820',
  '002790',
  '003570',
  '005070',
  '361610',
  '456040',
  '007310',
  '075580',
  '079900',
  '090460',
  '100090',
  '137310',
  '185750',
  '248070',
  '280360',
  '298050',
  '300720',
  '009450',
  '064960',
  '000080',
  '000210',
  '000670',
  '003090',
  '003240',
  '003850',
  '004000',
  '004490',
  '005300',
  '005690',
  '006340',
  '006650',
  '484870',
  '001340',
  '001390',
  '001570',
  '001680',
  '001940',
  '002240',
  '002310',
  '002350',
  '002710',
  '002840',
  '002900',
  '002960',
  '003000',
  '003160',
  '003300',
  '003620',
  '003720',
  '004700',
  '004710',
  '005010',
  '005180',
  '005420',
  '005610',
  '005680',
  '005720',
  '005950',
  '006110',
  '006380',
  '306200',
  '317450',
  '336370',
  '344820',
  '377740',
  '460860',
  '078520',
  '084010',
  '092200',
  '092230',
  '092790',
  '093050',
  '097520',
  '100840',
  '104700',
  '105630',
  '105840',
  '108320',
  '108670',
  '145720',
  '145990',
  '161000',
  '170900',
  '178920',
  '183190',
  '192650',
  '194370',
  '200880',
  '217590',
  '249420',
  '268280',
  '271940',
  '285130',
  '007690',
  '008730',
  '009160',
  '009290',
  '009900',
  '010690',
  '010780',
  '010820',
  '011930',
  '0120G0',
  '014820',
  '014830',
  '016380',
  '016590',
  '016800',
  '017810',
  '017900',
  '018250',
  '019170',
  '020000',
  '025540',
  '025860',
  '029460',
  '029530',
  '033240',
  '033270',
  '058430',
  '058650',
  '069260',
  '000430',
  '001060',
  '000020',
  '000040',
  '000220',
  '000230',
  '000300',
  '000390',
  '000480',
  '000490',
  '000520',
  '000850',
  '000860',
  '000890',
  '000910',
  '000950',
  '000970',
  '001020',
  '001070',
  '001080',
  '001130',
  '001210',
  '001360',
  '001380',
  '001420',
  '001460',
  '001520',
  '001550',
  '001560',
  '001620',
  '001630',
  '001770',
  '001780',
  '001790',
  '002070',
  '002100',
  '002140',
  '002170',
  '002200',
  '002210',
  '002220',
  '002360',
  '002390',
  '002450',
  '002600',
  '002630',
  '002690',
  '002720',
  '002760',
  '002820',
  '002880',
  '002920',
  '003060',
  '003080',
  '003120',
  '003200',
  '003220',
  '003350',
  '003520',
  '003610',
  '003650',
  '003680',
  '003780',
  '003830',
  '003920',
  '003960',
  '004090',
  '004100',
  '004250',
  '004310',
  '004380',
  '004410',
  '004430',
  '004440',
  '004450',
  '004540',
  '004560',
  '004720',
  '004770',
  '004830',
  '004840',
  '004870',
  '004890',
  '004910',
  '004920',
  '004980',
  '005030',
  '005500',
  '005750',
  '005800',
  '005820',
  '005870',
  '006090',
  '006570',
  '006660',
  '006740',
  '006890',
  '006980',
  '007160',
  '007210',
  '007280',
  '007460',
  '007570',
  '007590',
  '007610',
  '007980',
  '008040',
  '008250',
  '008260',
  '008350',
  '008420',
  '008490',
  '008500',
  '008700',
  '008870',
  '008970',
  '009140',
  '009190',
  '009200',
  '009270',
  '009310',
  '009320',
  '009460',
  '009470',
  '009580',
  '009680',
  '009770',
  '010040',
  '010100',
  '010580',
  '010640',
  '010660',
  '010770',
  '011000',
  '011090',
  '011150',
  '011230',
  '011280',
  '011300',
  '011330',
  '011390',
  '011500',
  '011690',
  '011700',
  '012160',
  '012200',
  '012280',
  '012610',
  '012690',
  '012800',
  '013520',
  '013870',
  '013890',
  '014160',
  '014280',
  '014440',
  '014530',
  '014580',
  '014710',
  '014910',
  '014990',
  '015230',
  '015260',
  '015590',
  '015890',
  '016090',
  '016450',
  '016580',
  '016740',
  '017040',
  '017180',
  '017370',
  '017550',
  '017860',
  '018470',
  '018500',
  '019180',
  '019490',
  '020760',
  '021050',
  '021820',
  '023000',
  '023150',
  '023450',
  '023800',
  '023810',
  '024070',
  '024090',
  '024890',
  '024900',
  '025000',
  '025560',
  '025620',
  '025750',
  '025820',
  '025890',
  '026940',
  '027740',
  '027970',
  '032560',
  '033250',
  '033530',
  '033920',
  '035150',
  '036580',
  '041650',
  '044380',
  '047400',
  '049800',
  '051630',
  '055490',
  '058730',
  '063160',
  '069460',
  '069730',
  '071090',
  '071950',
  '074610',
  '075180',
  '079430',
  '079980',
  '081000',
  '083420',
  '084680',
  '084870',
  '085310',
  '089470',
  '090080',
  '090350',
  '090370',
  '092220',
  '092440',
  '092780',
  '093240',
  '100250',
  '101530',
  '102260',
  '102460',
  '109070',
  '111110',
  '111380',
  '119650',
  '120030',
  '123700',
  '133820',
  '134380',
  '134790',
  '136490',
  '139990',
  '143210',
  '145210',
  '155660',
  '163560',
  '210540',
  '213500',
  '214330',
  '214390',
  '214420',
  '226320',
  '234080',
  '241590',
  '248170',
  '264900',
  '271980',
  '272550',
  '293480',
  '298000',
  '308170',
  '372910',
  '378850',
  '446070',
  '460850',
  '462520']}

True

In [86]:
sector['제조']

['005930',
 '000660',
 '009150',
 '005380',
 '373220',
 '329180',
 '000270',
 '034020',
 '012450',
 '207940',
 '012330',
 '006400',
 '267260',
 '042660',
 '010120',
 '068270',
 '066570',
 '298040',
 '042700',
 '005490',
 '011070',
 '000150',
 '010130',
 '051910',
 '010140',
 '064350',
 '079550',
 '272210',
 '033780',
 '096770',
 '003670',
 '278470',
 '047810',
 '010950',
 '000880',
 '007660',
 '003230',
 '353200',
 '161390',
 '001440',
 '267270',
 '062040',
 '009830',
 '034220',
 '454910',
 '000990',
 '011790',
 '090430',
 '241560',
 '000100',
 '066970',
 '018880',
 '336260',
 '128940',
 '271560',
 '082740',
 '004020',
 '002380',
 '000500',
 '103590',
 '450080',
 '051900',
 '204320',
 '489790',
 '005850',
 '017800',
 '014680',
 '011780',
 '011170',
 '020150',
 '302440',
 '097950',
 '383220',
 '007810',
 '439260',
 '457190',
 '483650',
 '009420',
 '071970',
 '007340',
 '093370',
 '103140',
 '112610',
 '004370',
 '161890',
 '192820',
 '011210',
 '120110',
 '322000',
 '006280',
 '077970',
 '195870',
 '281820',
 '298020',
 '017960',
 '069620',
 '073240',
 '001430',
 '001820',
 '002790',
 '003570',
 '005070',
 '361610',
 '456040',
 '007310',
 '075580',
 '079900',
 '090460',
 '100090',
 '137310',
 '185750',
 '248070',
 '280360',
 '298050',
 '300720',
 '009450',
 '064960',
 '000080',
 '000210',
 '000670',
 '003090',
 '003240',
 '003850',
 '004000',
 '004490',
 '005300',
 '005690',
 '006340',
 '006650',
 '484870',
 '001340',
 '001390',
 '001570',
 '001680',
 '001940',
 '002240',
 '002310',
 '002350',
 '002710',
 '002840',
 '002900',
 '002960',
 '003000',
 '003160',
 '003300',
 '003620',
 '003720',
 '004700',
 '004710',
 '005010',
 '005180',
 '005420',
 '005610',
 '005680',
 '005720',
 '005950',
 '006110',
 '006380',
 '306200',
 '317450',
 '336370',
 '344820',
 '377740',
 '460860',
 '078520',
 '084010',
 '092200',
 '092230',
 '092790',
 '093050',
 '097520',
 '100840',
 '104700',
 '105630',
 '105840',
 '108320',
 '108670',
 '145720',
 '145990',
 '161000',
 '170900',
 '178920',
 '183190',
 '192650',
 '194370',
 '200880',
 '217590',
 '249420',
 '268280',
 '271940',
 '285130',
 '007690',
 '008730',
 '009160',
 '009290',
 '009900',
 '010690',
 '010780',
 '010820',
 '011930',
 '0120G0',
 '014820',
 '014830',
 '016380',
 '016590',
 '016800',
 '017810',
 '017900',
 '018250',
 '019170',
 '020000',
 '025540',
 '025860',
 '029460',
 '029530',
 '033240',
 '033270',
 '058430',
 '058650',
 '069260',
 '000430',
 '001060',
 '000020',
 '000040',
 '000220',
 '000230',
 '000300',
 '000390',
 '000480',
 '000490',
 '000520',
 '000850',
 '000860',
 '000890',
 '000910',
 '000950',
 '000970',
 '001020',
 '001070',
 '001080',
 '001130',
 '001210',
 '001360',
 '001380',
 '001420',
 '001460',
 '001520',
 '001550',
 '001560',
 '001620',
 '001630',
 '001770',
 '001780',
 '001790',
 '002070',
 '002100',
 '002140',
 '002170',
 '002200',
 '002210',
 '002220',
 '002360',
 '002390',
 '002450',
 '002600',
 '002630',
 '002690',
 '002720',
 '002760',
 '002820',
 '002880',
 '002920',
 '003060',
 '003080',
 '003120',
 '003200',
 '003220',
 '003350',
 '003520',
 '003610',
 '003650',
 '003680',
 '003780',
 '003830',
 '003920',
 '003960',
 '004090',
 '004100',
 '004250',
 '004310',
 '004380',
 '004410',
 '004430',
 '004440',
 '004450',
 '004540',
 '004560',
 '004720',
 '004770',
 '004830',
 '004840',
 '004870',
 '004890',
 '004910',
 '004920',
 '004980',
 '005030',
 '005500',
 '005750',
 '005800',
 '005820',
 '005870',
 '006090',
 '006570',
 '006660',
 '006740',
 '006890',
 '006980',
 '007160',
 '007210',
 '007280',
 '007460',
 '007570',
 '007590',
 '007610',
 '007980',
 '008040',
 '008250',
 '008260',
 '008350',
 '008420',
 '008490',
 '008500',
 '008700',
 '008870',
 '008970',
 '009140',
 '009190',
 '009200',
 '009270',
 '009310',
 '009320',
 '009460',
 '009470',
 '009580',
 '009680',
 '009770',
 '010040',
 '010100',
 '010580',
 '010640',
 '010660',
 '010770',
 '011000',
 '011090',
 '011150',
 '011230',
 '011280',
 '011300',
 '011330',
 '011390',
 '011500',
 '011690',
 '011700',
 '012160',
 '012200',
 '012280',
 '012610',
 '012690',
 '012800',
 '013520',
 '013870',
 '013890',
 '014160',
 '014280',
 '014440',
 '014530',
 '014580',
 '014710',
 '014910',
 '014990',
 '015230',
 '015260',
 '015590',
 '015890',
 '016090',
 '016450',
 '016580',
 '016740',
 '017040',
 '017180',
 '017370',
 '017550',
 '017860',
 '018470',
 '018500',
 '019180',
 '019490',
 '020760',
 '021050',
 '021820',
 '023000',
 '023150',
 '023450',
 '023800',
 '023810',
 '024070',
 '024090',
 '024890',
 '024900',
 '025000',
 '025560',
 '025620',
 '025750',
 '025820',
 '025890',
 '026940',
 '027740',
 '027970',
 '032560',
 '033250',
 '033530',
 '033920',
 '035150',
 '036580',
 '041650',
 '044380',
 '047400',
 '049800',
 '051630',
 '055490',
 '058730',
 '063160',
 '069460',
 '069730',
 '071090',
 '071950',
 '074610',
 '075180',
 '079430',
 '079980',
 '081000',
 '083420',
 '084680',
 '084870',
 '085310',
 '089470',
 '090080',
 '090350',
 '090370',
 '092220',
 '092440',
 '092780',
 '093240',
 '100250',
 '101530',
 '102260',
 '102460',
 '109070',
 '111110',
 '111380',
 '119650',
 '120030',
 '123700',
 '133820',
 '134380',
 '134790',
 '136490',
 '139990',
 '143210',
 '145210',
 '155660',
 '163560',
 '210540',
 '213500',
 '214330',
 '214390',
 '214420',
 '226320',
 '234080',
 '241590',
 '248170',
 '264900',
 '271980',
 '272550',
 '293480',
 '298000',
 '308170',
 '372910',
 '378850',
 '446070',
 '460850',
 '462520']

In [89]:
krxList

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId,Sector
0,005930,KR7005930003,삼성전자,KOSPI,NaN,343000,1,6000,1.78,343000,345500,332500,17548685,5970562049352,2005273562544000,5846278608,STK,기타
1,000660,KR7000660001,SK하이닉스,KOSPI,NaN,2382000,1,94000,4.11,2381000,2400000,2286000,3644469,8608079280084,1697657033430000,712702365,STK,기타
2,402340,KR7402340004,SK스퀘어,KOSPI,NaN,1501000,1,88000,6.23,1440000,1510000,1380000,872218,1275791203000,198069537386000,131958386,STK,기타
3,005935,KR7005931001,삼성전자우,KOSPI,NaN,224000,1,8000,3.70,220000,224500,216000,3341287,739325628500,179731149472000,802371203,STK,기타
4,009150,KR7009150004,삼성전기,KOSPI,NaN,2048000,1,49000,2.45,2042000,2071000,1970000,1084769,2202475204500,152972689408000,74693696,STK,기타
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2870,011155,KR7011151008,CJ씨푸드1우,KOSPI,NaN,9710,2,-10,-0.10,9720,9720,9660,342,3322620,1942000000,200000,STK,기타
2871,004415,KR7004411005,서울식품우,KOSPI,NaN,7760,2,-80,-1.02,7600,7810,7600,1473,11423580,1726212000,222450,STK,기타
2872,032685,KR7032681009,소프트센우,KOSDAQ,중견기업부,19910,2,-690,-3.35,20100,21200,19910,250,5003830,1420817420,71362,KSQ,기타
2873,266170,KR7266170000,레드우즈,KONEX,일반기업부,1050,0,0,0.00,0,0,0,0,0,1366092000,1301040,KNX,기타
2874,279060,KR7279060008,이노벡스,KONEX,일반기업부,115,0,0,0.00,0,0,0,0,0,1127904590,9807866,KNX,기타

In [96]:
import pandas as pd

df_price = pd.DataFrame({
    '종목코드': ['005930', '000660', '035420']
})

df_info = pd.DataFrame({
    '종목코드': ['005930', '000660', '035420'],
    '종목명': ['삼성전자', 'SK하이닉스', 'NAVER']
})

In [98]:
code_dict = df_info.set_index('종목코드')['종목명']
code_dict
df_price['종목명'] = df_price['종목코드'].map(code_dict)

In [99]:
df_price

     종목코드     종목명
0  005930    삼성전자
1  000660  SK하이닉스
2  035420   NAVER